### ISSUE TITLE
iNes mapper #3914 is not supported at all.

### ISSUE THREAD

**Issue by intMadMax** [ClusterM/nes-warface#1]
Hi, Great project! Just wanted to run nes files using emulator, but it seems that there is no such mapper included in fceux original binaries. I used to build your fceux-fork, but nothing changed. Would you be kind to help me?

![image](https://user-images.githubusercontent.com/124444378/221629117-079f601f-9eb2-47a6-934d-d5d71340874d.png)

**Comment by ClusterM** [comment]
Oops, my mistake. I forgot to add this mapper to my fork. Please try it now. You can download compiled binaries in GitHub Actions artifacts.

**Comment by intMadMax** [comment]
Great!
